#!/usr/bin/with-contenv bash

cat <<"EOF"
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
         _               _
    __ _| |__   ___  ___| |_
   / _` | '_ \ / _ \/ __| __/
  | (_| | | | | (_) \__ \ |_
   \__, |_|_|_|\___/|___/\__|
   |___/      /   _ \
          (¯\| o (@) |/¯)
           \_  .___.  _/
            /   !_!   \
           /_.--._.--._\

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
EOF

PLUGIN_LIST="${PLUGIN_LIST:-trakt}"

if [[ $PLUGIN_LIST != "" ]]; then
     apt-get update && apt-get install -y unzip && \
     mkdir -p "/config/Library/Application Support/Plex Media Server/Plug-ins/"
fi

if [[ $PLUGIN_LIST == *"trakt"* ]]; then
     # install the trakt plugin
     echo "### Installing Trakt Plugin ###"
     wget https://github.com/trakt/Plex-Trakt-Scrobbler/releases/download/v1.3.3/trakt_for_plex-1.3.3-7f0f38e-linux_x86_64.zip && \
     rm -rf "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle" && \
     unzip trakt_for_plex-1.3.3-7f0f38e-linux_x86_64.zip -d "/config/Library/Application Support/Plex Media Server/Plug-ins/" && \
     rm trakt_for_plex-1.3.3-7f0f38e-linux_x86_64.zip
fi

if [[ $PLUGIN_LIST == *"subzero"* ]]; then
     # install the subzero plugin
     echo "### Installing Subzero Plugin ###"
     wget https://github.com/pannal/Sub-Zero.bundle/releases/download/2.6.5.3109/Sub-Zero.bundle-2.6.5.3109.zip && \
     rm -rf "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle" && \
     unzip Sub-Zero.bundle-2.6.5.3109.zip -d "/config/Library/Application Support/Plex Media Server/Plug-ins/" && \
     rm Sub-Zero.bundle-2.6.5.3109.zip
fi

# allow all users to access GPU for hardware acceleration
chmod -R 777 /dev/dri

